apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: todo-app
  labels:
    app: todo-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATA_DIR: "/app/data"
  APP_VERSION: "1.0.0"
  # AWS specific configs (if needed)
  AWS_REGION: "ap-south-1"
